services:
  - type: web
    name: clipforge
    runtime: node
    repo: https://github.com/ibrahimabubacar788-tech/clipforge
    branch: main
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/ready
    autoDeploy: true
    plan: free
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: clipforge-db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_HIGHLIGHT_MODEL
        value: gpt-6-luna

databases:
  - name: clipforge-db
    plan: free
    region: frankfurt
    postgresMajorVersion: "18"
