import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { createApp } from "../server/app.js";

async function app() { const dir = await mkdtemp(join(tmpdir(), "clipforge-")); const server = createApp({ root: process.cwd(), dbFile: join(dir, "db.json"), storageDir: join(dir, "storage") }); await new Promise((resolve) => server.listen(0, resolve)); return { server, base: `http://127.0.0.1:${server.address().port}` }; }
async function request(base, path, method = "GET", body, token) { const response = await fetch(`${base}${path}`, { method, headers: { "content-type": "application/json", ...(token ? { authorization: `Bearer ${token}` } : {}) }, body: body && JSON.stringify(body) }); return { status: response.status, body: response.status === 204 ? null : await response.json() }; }
test("auth, project, and queued render flow are scoped to the signed-in user", async (t) => { const { server, base } = await app(); t.after(() => server.close()); const registered = await request(base, "/api/auth/register", "POST", { email: "creator@example.com", password: "password-123" }); assert.equal(registered.status, 201); const token = registered.body.token; const project = await request(base, "/api/projects", "POST", { name: "Show" }, token); const video = await request(base, "/api/videos", "POST", { projectId: project.body.project.id, name: "Episode", duration: 60 }, token); const clip = await request(base, "/api/clips", "POST", { videoId: video.body.video.id, start: 2, end: 20, format: "9:16", captions: true }, token); assert.equal(clip.status, 202); assert.equal(clip.body.job.status, "queued"); await new Promise((resolve) => setTimeout(resolve, 300)); const clips = await request(base, "/api/clips", "GET", undefined, token); assert.equal(clips.body.clips[0].status, "ready"); assert.match(clips.body.clips[0].downloadUrl, /^\/storage\/exports\//); });
test("clip validation rejects ranges outside the source duration", async (t) => { const { server, base } = await app(); t.after(() => server.close()); const user = await request(base, "/api/auth/register", "POST", { email: "range@example.com", password: "password-123" }); const project = await request(base, "/api/projects", "POST", { name: "P" }, user.body.token); const video = await request(base, "/api/videos", "POST", { projectId: project.body.project.id, duration: 10 }, user.body.token); const bad = await request(base, "/api/clips", "POST", { videoId: video.body.video.id, start: 0, end: 11 }, user.body.token); assert.equal(bad.status, 422); });
